school/enroll/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from enroll import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'school.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name = 'index'),
    url(r'^create/$', views.create, name = 'create'),
    url(r'^(?P<student_id>\d+)/$', views.detail, name = 'detail'),
    
)

school/school/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'school.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^enroll/', include('enroll.urls', namespace = "enroll")),
    #url(r'^$', include('enroll.urls', namespace = "enroll")),
)

school/enroll/models.py
from django.db import models
class student_info(models.Model):
	student_name = models.CharField(max_length = 100)
	student_age = models.IntegerField(default = 0)
	student_gender = models.CharField(max_length = 10)
	student_major = models.CharField(max_length = 100)

# Create your models here.

school/enroll/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from enroll.models import student_info
from django.core.urlresolvers import reverse

def index(request):
	stu_list=student_info.objects.all()
	return render(request, 'enroll/index.html',{'stu_list':stu_list})
def create(request):
	if request.method == 'GET':
		return render(request, 'enroll/create.html')
	elif request.method == 'POST':
		student = student_info(student_name=request.POST['name'], student_age=request.POST['age'], student_gender = request.POST['gender'], student_major = request.POST['major'])
		student.save()
		return HttpResponseRedirect(reverse('enroll:detail', args=(student.id,)))
def detail(request, student_id):
	try:
		student=student_info.objects.get(pk=student_id)
	except student_info.DoesNotExist:
		raise Http404("student does not exist")
	return render(request, 'enroll/detail.html', {'student':student})

# Create your views here.

school/enroll/templates/enroll/create.html
<h2>Enroll Form</h2>
<form action="{% url 'enroll:create' %}" method="post">
    {% csrf_token %}
        name: <input type="text" name="name"/><br/>
        age: <input type="text" name="age"/><br/>
        gender: <input type = "radio" name="gender" value="male">male</input>
    <input type = "radio" name="gender" value="female">female</input><br/>
        major:<input type = "text" name="major"/><br/><br/>
        <input type="submit" value="submit"/>
    </form>

school/enroll/templates/enroll/detail.html
<h1>{{ student.student_name }}</h1>
<p>age: {{ student.student_age }}</p>
<p>gender: {{ student.student_gender }}</p>
<p>major: {{ student.student_major }}</p>

school/enroll/templates/enroll/index.html
{% if stu_list %}
<ul>
    {% for s in stu_list %}
    <li><a href="/enroll/{{ s.id }}/">{{ s.student_name }}</a> </li>
    {% endfor %}
    </ul>
{% else %}
<p>name is unavailable</p>
{% endif %}

<button><a href="/enroll/create/">enroll</a> </button>